### ISSUE TITLE
Using allow.na = TRUE with assert(is_uniq, ...)

### ISSUE THREAD

**Issue by dctanugi** [ropensci/assertr#105]
The `is_uniq` function takes an optional argument called `allow.na`. However, the documentation does not make it clear how to apply this argument in the context an `assert` operation.

```
# this works
mtcars %>% assert(is_uniq, qsec)

# this throws an error
mtcars %>% assert(is_uniq(allow.na = TRUE), qsec)
```

Is there a good way to do this? If so, it would be great to add it to the examples provided in the is_uniq function documentation.

**Comment by tonyfischetti** [comment]
That's a great point; it isn't at all clear
The problem is that `assert` expects a fully-formed function
The way to handle the situation you described is by using a lambda/anonymous function
like so
 ```
mtcars %>% assert(function(x){is_uniq(x, allow.na=TRUE)}, qsec)

# or

is_uniq_allow_na <- function(x){
  is_uniq(x, allow.na=TRUE)
}

mtcars %>% assert(is_uniq_allow_na, qsec)
```

It isn't pretty, I'll admit, but the flexibility of using fully-formed functions in `assert` is
central to the package's flexibility

I'll update the documentation--thanks for the suggestion!
