### ISSUE TITLE
How to get the validation report?

### ISSUE THREAD

**Issue by easonktsai** [ropensci/assertr#124]
I am new for r language and I try to get the error report in the following snippet. 

```r
our.data %>%
  chain_start %>%
  assert(within_bounds(1,2), mpg) %>%
  chain_end(error_fun=error_report)
```

I want to get the compeleted validation report. How can I export the report as JSON format or any other format type?

Thanks.

**Comment by tonyfischetti** [comment]
Instead of `chain_end(error_fun=error_report)` try `(chain_end(error_fun=error_return)` or `(chain_end(error_fun=error_df_return)` and assign that to a variable

The first returns an object of the type `assertr_assert_error`. Use the `str` function to look inside at the information
The second returns a `data.frame` containing all the error information.
If you want to export it to JSON, you have to convert the `data.frame` to JSON. The easiest way to do that is probably to use the `jsonlite` package

I hope you figure it out. I'll close this issue for now but if it's still something you are stuck on, please re-comment
